# Annotation file list
ANNOT_FILE_LIST:
- "../dataset/annots/abltmr_ret.json"


# Ground-truth
GT_LABEL_NAME_LIST:
- abltmr_ret


# Cloud Volume path config

# Google bucket paths
EM_PATH: "precomputed://gs://lee-mouse-spinal-cord-001-raw/dorsalhorn_ret"
SEG_PATH: "precomputed://gs://lee-mouse-spinal-cord-001-segmentations-prod/ng/spinal-003-big-sv/seg/dorsalhorn_ret"
SEG_MESHES: "abltmr_ret_meshes"

MIP_EM_VOL: !!python/tuple [32,32,45]
MIP_SEG_VOL: !!python/tuple [32,32,45]

# Model path and config
INPUT_SHAPE: !!python/tuple [129, 129, 129, 1]

MODELS_2_USE:
    microns: "models/microns/model.ckpt-216000.training_tf2resaved-1"
    h01: "models/h01/model.ckpt-355200.tf2resaved-1"
    sp: "/n/data3_vast/hms/neurobio/htem2/users/kd193/train_embedding_model/ckpt/spinal_cord_embed_model_v4/ckpt-3516"

ANNOTS_OUTPUT_DIR: "../dataset/annots_processed"

# Caveclient
CAVECLIENT_DATASTACK: ""

# Script params
NG_MIP: !!python/tuple [16,16,45] # resolution of annotations
VOL_MIP: !!python/tuple [32,32,45] # expected resolution moving forward
OVERWRITE: False

ROOT_SAVE_FOLDER: "../dataset/embeddings"
FOLDER_EXT: ""

DATA_FOLDER: "data"
EMBED_FOLDER: "embed"

TRAINED_AGG_RADIUS_UM: 20

EMBED_AGG_RADIUS_UM: 10
OVERWRITE_FILES: False

# Save 3d volume cutouts
SAVE_VOL_CUTOUTS: True

# skip embedding 3d cutouts
SKIP_EMBEDDING: False
