CLASS_NAMES: 
- cltmr
- cltmrunlabeled
- abltmr
- adltmr
- chtmrnp
- othersn
- adhtmrp
- chtmrp
- dend_synapses
- nonsensory
- cold

# Cloud Volume path config

# # Mrgd dataset
# EM_PATH: "precomputed://gs://htem_dorsalhorn_mrgd_r1093/dorsal_sections/dorsal_sections_0-500"
# SEG_PATH: "graphene://https://cave.fanc-fly.com/segmentation/table/mouse_dorsal_spine"
# SEG_MESHES: "mrgd_meshes"

# MIP_EM_VOL: !!python/tuple [4,4,45]
# MIP_SEG_VOL: !!python/tuple [32,32,45]

# Spinal cord DS - cltmr
EM_PATH: "precomputed://gs://lee-mouse-spinal-cord-001-raw/sharded"
SEG_PATH: "graphene://https://cave.fanc-fly.com/segmentation/table/wclee_mouse_spinalcord_cltmr"
SEG_MESHES: "spinal_cord_meshes"

MIP_EM_VOL: !!python/tuple [32,32,45]
MIP_SEG_VOL: !!python/tuple [32,32,45]

# Model path and config
INPUT_SHAPE: !!python/tuple [129, 129, 129, 1]

# Caveclient
CAVECLIENT_DATASTACK: "wclee_mouse_spinalcord_cltmr"

# Script params
NG_MIP: !!python/tuple [32,32,45] # resolution of annotations
VOL_MIP: !!python/tuple [32,32,45] # expected resolution moving forward
OVERWRITE: False

ROOT_SAVE_FOLDER: "../dataset/embeddings"
FOLDER_EXT: ""

DATA_FOLDER: "data"
EMBED_FOLDER: "embed"

TRAINED_AGG_RADIUS_UM: 20

EMBED_AGG_RADIUS_UM: 10